colorScheme = "blowfish"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
enableStructuredBreadcrumbs = true
highlightCurrentMenuArea = true
smartTOC = true

disableImageOptimization = false
disableImageOptimizationMD = false

defaultFeaturedImage = "img/photos/article-default.jpg"
defaultBackgroundImage = "img/photos/home-hero.jpg"
defaultSocialImage = "img/photos/cityscape.jpg"
hotlinkFeatureImage = true

fingerprintAlgorithm = "sha512"

mainSections = ["life", "office"]

[header]
  layout = "fixed"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "background"
  homepageImage = "img/photos/home-hero.jpg"
  showRecent = true
  showRecentItems = 12
  showMoreLink = true
  showMoreLinkDest = "/life/"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true
  disableHeroImageFilter = false

[article]
  showDate = true
  showAuthor = true
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showCategories = true
  showTags = true
  showWordCount = false
  showZenMode = true
  showRelatedContent = true
  relatedContentLimit = 3

[list]
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  showSummary = true
  showBreadcrumbs = true
  showTableOfContents = false
  showCards = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false

[taxonomy]
  showHero = true
  heroStyle = "background"
  showBreadcrumbs = true
  cardView = true

[term]
  showHero = false
  showBreadcrumbs = true
  showTableOfContents = false
  cardView = true
  groupByYear = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[baiduAnalytics]
  siteId = "7108ccadd9c5e013829dbb193f5b1d0d"

[icp]
  display = true
  icpNumber = "苏ICP备2026011017号-5"
  icpUrl = "https://beian.miit.gov.cn/"
  gonganNumber = "苏公网安备32010602012446号"
  gonganUrl = "https://beian.mps.gov.cn/#/query/webSearch?code=32010602012446"
