networks:
  tiny-sparrow-network:
    external: false

services:
  # Hugo 静态网站
  xiaolin-life-website:
    image: ghcr.nju.edu.cn/xiaolinstar/xiaolin-life:main
    container_name: xiaolin-life-website
    volumes:
      - ./volumes/website/logs:/var/log/nginx
    networks:
      - tiny-sparrow-network
    ports:
      - "8081:8080"
    environment:
      TZ: Asia/Shanghai
