apiVersion: apps/v1
kind: Deployment
metadata:
  name: vitepress-website-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vitepress-website-pod
  template:
    metadata:
      labels:
        app: vitepress-website-pod
    spec:
      containers:
      - name: vitepress-website-container
        image: xxl1997/xiaolin-docs:0.0.1
        ports:
        - containerPort: 8080
        env:
        - name: TZ
          value: Asia/Shanghai
        volumeMounts:
        - name: logs
          mountPath: /var/log/nginx
      volumes:
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: vitepress-website-svc
spec:
  selector:
    app: vitepress-website-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
