server {
    listen 127.0.0.1:8081;
    listen [::]:127.0.0.1:8081;

    location /stub_status {
        stub_status on;
        access_log off;
        allow 127.0.0.1;
        allow 172.16.0.0/12;
        deny all;
    }
}
