server {
    listen       8080;
    listen  [::]:8080;
    # 开启ssl，使用https
    # ssl;
    # 域名 部署服务器IP 本地环回地址
    server_name  xiaolin.fun localhost;

    access_log  /var/log/nginx/host.access.log  main;

    # 静态资源代理，前端Web服务器
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
    #error_page  404              /404.html;

    # redirect server error pages to the assets page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
