version: '1.0'
name: main-pipeline
displayName: main-pipeline
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - main
stages:
  - name: stage_docker_build
    displayName: 镜像构建
    strategy: naturally
    trigger: auto
    executor:
      - xingxiaolin
    steps:
      - step: build@docker
        name: build_docker
        displayName: 镜像构建
        type: cert
        certificate: 63ef6240-4843-013e-a97a-362c63ba4791
        tag: ${GITEE_REPO}:v0.${GITEE_PIPELINE_BUILD_NUMBER}
        dockerfile: ./Dockerfile
        context: ''
        artifacts: []
        isCache: false
        parameter: {}
        notify: []
        strategy:
          retry: '0'
