server {
    listen       80;
    listen  [::]:80;
    server_name  xiaolin.fun www.xiaolin.fun localhost;

    root   /usr/share/nginx/html;
    index  index.html index.htm;

    access_log  /var/log/nginx/host.access.log  main;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(md|txt)$ {
        root   /usr/share/nginx/html;
        default_type text/plain;
        charset utf-8;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
